# just demo
# author: lilzh
# TODO: ssh,
# TODO: java, db, 

# centos:centos7.5.1804
FROM centos:centos7.5.1804

MAINTAINER from lilzh.com by lilzhang90s (lilzhang90s@163.com)

# TODO: RUN

# -> 86
EXPOSE 22

CMD ["tail", "-f", "/root/anaconda-ks.cfg"]