# just demo
# author: lilzh
# TODO: ssh,
# TODO: java, db, 

# centos:centos7.5.1804
FROM centos:centos7.5.1804

MAINTAINER from lilzh.com by lilzhang90s (lilzhang90s@163.com)

# -> 86
EXPOSE 22

ENTRYPOINT ["tail", "-f", "/var/log"]