# just demo
# author: lilzh
# TODO: java, db

FROM 10.8.0.16:5000/demo-java:0.0.2

MAINTAINER from lilzh.com by lilzhang90s (lilzhang90s@163.com)

ADD run.sh /run.sh

RUN chmod +x /run.sh

EXPOSE 8089

CMD ["/run.sh"]