---
apiVersion: v1
kind: Pod
metadata:
  name: boot-demo
  namespace: demo-test
  labels:
    app: boot-demo
spec:
  containers:
    - name: boot-demo
      image: 10.8.0.16:5000/boot-demo:0.0.1
      ports:
        - containerPort: 8089
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: boot-demo
  namespace: demo-test
spec:
  replicas: 2
  template:
    metadata:
      namespace: demo-test
      labels:
        app: boot-demo
    spec:
      containers:
        - name: boot-demo
          image: 10.8.0.16:5000/boot-demo:0.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: boot-demo
  namespace: demo-test
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8089
  selector:
    app: boot-demo